import { Plus_Jakarta_Sans } from "next/font/google";
import 'remixicon/fonts/remixicon.css'
import "./globals.css";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import { ProductContextProvider } from "@/components/ProductContext";

const plusJakartaSans = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={plusJakartaSans.className}>
        <Navbar />
        <ProductContextProvider>
          {children}
        </ProductContextProvider>
        <Footer />
      </body>
    </html>
  );
}
